version: '3.8'

services:
  bwc_ambassador:
    image: bwc_ambassador
    build:
      context: .
      dockerfile: ./Dockerfile
    # environment:
    #   NODE_ENV: production
    ports:
      - 3001:4200
    volumes:
      - .:/app
      - /app/node_modules
