version: '3.8'

services:
  ng_bwc_ambassador:
    image: ng_bwc_ambassador
    build:
      context: .
      dockerfile: ./Dockerfile
    # environment:
    #   NODE_ENV: production
    ports:
      - 3001:4200
    # volumes:
    #   - .:/app
    #   - /app/node_modules
